remote_theme: daattali/beautiful-jekyll@6.0.1
#####################################################################
######## My Website Configuration File
########Refer to 
######## https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
######## for more configuration options
#####################################################################

#Name of Website
title: My Profile Website

# Your name to show in the footer
author: Frank Lamptey

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Resume: "myresume"
  More:
    - Projects:
        - Simple Auth & CRUD API: "https://github.com/KitKat-Frankie/into_back_end"
    - My Badges: "https://www.credly.com/users/frank-lamptey.e0602805/badges#credly"
    - Animations: "animations"

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
